apiVersion: v1
kind: Pod
metadata:
  name: gopher-pod
spec:
  containers:
    - name: gopher-container
      image: m.daocloud.io/docker.io/library/busybox:latest
      command: ["sh", "-c", "env && echo Hello, Kubernetes! && sleep 3600"]
      resources:
        requests:
          jiangyuan.com/gpu: "1"
        limits:
          jiangyuan.com/gpu: "1"